---

- hosts: all
  tasks:
    - shell: echo 'hello world'

    - name: Run myprog
#     debugger: always
      command: ls
      register: result
      ignore_errors: true
    - debug: var=result
    - debug: msg="First line is {{ result.stdout_lines[0] }}"
    - debug: msg="First line is {{ result['stdout_lines'][0] }}"
    - debug: msg="Ansible facts OS family {{ ansible_facts.os_family }}"
    - debug: msg="All Ansible fact keys {{ ansible_facts.keys() }}"
    - debug: msg="Hostvars {{ hostvars }}"
    - debug: msg="Hostvar keys {{ hostvars.localhost.keys() }}"
    - debug: msg="All Ansible fact keys {{ ansible_facts.keys() }}"
    - debug: msg="Facts hostname {{ ansible_facts.hostname }}"
